ALTER TABLE "PropFirmChallenge"
ADD COLUMN "ruleProfile" TEXT NOT NULL DEFAULT 'CUSTOM',
ADD COLUMN "dailyResetTimeZone" TEXT NOT NULL DEFAULT 'UTC',
ADD COLUMN "warningThreshold" INTEGER NOT NULL DEFAULT 80;

